services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: auth-data
      mountPath: /app/auth_info
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: false
    buildFilter:
      paths:
        - src/**
        - index.js
        - package.json
    startupProbe:
      path: /health
      failureThreshold: 10
      periodSeconds: 10
    resources:
      cpu: 0.5
      memory: 512Mi

  # Add a cron job to keep the instance alive
  - type: cron
    name: keep-alive
    schedule: "*/5 * * * *"
    command: curl $RENDER_EXTERNAL_URL/health
