name: Deploy WhatsApp Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    steps:
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: srv-cv9iqr3tq21c73bknr2g
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "accept: application/json" \
          -H "authorization: Bearer $RENDER_API_KEY" \
          -H "content-type: application/json" \
          -d '{
            "clearCache": "clear"
          }'
