name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Download auth state
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: auth-state
          path: auth_info

      - name: Install dependencies
        run: npm ci
          
      - name: Install sharp
        run: npm install --platform=linux --arch=x64 sharp
          
      - name: Start bot
        run: |
          echo "Starting WhatsApp bot..."
          node index.js
        env:
          CI: true
          NODE_ENV: production
          AUTO_READ_STATUS: ${{ secrets.AUTO_READ_STATUS }}
          ANTI_CALL: ${{ secrets.ANTI_CALL }}
          WELCOME_MESSAGE: ${{ secrets.WELCOME_MESSAGE }}
          GOODBYE_MESSAGE: ${{ secrets.GOODBYE_MESSAGE }}

      - name: Save auth state
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auth-state
          path: auth_info
          retention-days: 1
